name: Build & Push Microservices

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # IAM SERVICE
      - name: Build IAM-Service
        uses: docker/build-push-action@v4
        with:
          context: ./iam-service
          push: true
          tags: datdevv/iam-service:latest

      # PATIENT SERVICE
      - name: Build Patient-Service
        uses: docker/build-push-action@v4
        with:
          context: ./patient-service
          push: true
          tags: datdevv/patient-service:latest

      # TESTORDER SERVICE
      - name: Build Testorder-Service
        uses: docker/build-push-action@v4
        with:
          context: ./testorder-services
          push: true
          tags: datdevv/testorder-service:latest

      # WAREHOUSE SERVICE
      - name: Build Warehouse-Service
        uses: docker/build-push-action@v4
        with:
          context: ./warehouse-service
          push: true
          tags: datdevv/warehouse-service:latest

      # INSTRUMENT SERVICE
      - name: Build Instrument-Service
        uses: docker/build-push-action@v4
        with:
          context: ./instrument-service
          push: true
          tags: datdevv/instrument-service:latest

      # MONITORING SERVICE
      - name: Build Monitoring-Service
        uses: docker/build-push-action@v4
        with:
          context: ./monitoring-service
          push: true
          tags: datdevv/monitoring-service:latest

      # NOTIFICATION SERVICE
      - name: Build Notification-Service
        uses: docker/build-push-action@v4
        with:
          context: ./notification-service
          push: true
          tags: datdevv/notification-service:latest

      # API GATEWAY
      - name: Build API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: datdevv/api-gateway:latest

      # EUREKA SERVER
      - name: Build Eureka-Server
        uses: docker/build-push-action@v4
        with:
          context: ./discovery-server
          push: true
          tags: datdevv/eureka-service:latest
