name: Build & Push (Only Changed Services)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    environment: docker
    outputs:
      changed: ${{ steps.collect.outputs.changed }}
    steps:
      - uses: actions/checkout@v3

      # Detect changes using dorny
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            iam:               "iam-service/**"
            patient:           "patient-service/**"
            testorder:         "testorder-services/**"
            warehouse:         "warehouse-service/**"
            instrument:        "instrument-service/**"
            monitoring:        "monitoring-service/**"
            notification:      "notification-service/**"
            gateway:           "api-gateway/**"
            eureka:            "discovery-server/**"

      # Convert results to JSON array []
      - id: collect
        run: |
          changes=()

          for service in iam patient testorder warehouse instrument monitoring notification gateway eureka; do
            if [ "${{ steps.filter.outputs[service] }}" = "true" ]; then
              changes+=("\"$service\"")
            fi
          done

          json="[$(IFS=,; echo "${changes[*]}")]"
          echo "changed=$json" >> $GITHUB_OUTPUT

          echo "Detected changes: $json"

  build:
    needs: detect-changes
    runs-on: ubuntu-latest

    # Skip nếu không có service thay đổi
    if: ${{ needs.detect-changes.outputs.changed != '[]' }}

    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed) }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: datdevv/${{ matrix.service }}:latest
